package:
  name: cert-manager-1.13
  # See https://cert-manager.io/docs/installation/supported-releases/ for upstream-supported versions
  version: 1.13.0
  epoch: 1
  description: Automatically provision and manage TLS certificates in Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cert-manager=${{package.full-version}}

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - make
      - curl
      - jq

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cert-manager/cert-manager
      tag: v${{package.version}}
      expected-commit: d34bd7aa15055b428bf865851bc420412f3710e6

  # the makefile hardcodes the requirement for some container runtime (CTR), even when we don't need it
  # to workaround, set CTR to anything $(command -v)able
  - runs: |
      make CTR=make _bin/server/controller-linux-$(go env GOARCH)
      make CTR=make _bin/server/webhook-linux-$(go env GOARCH)
      make CTR=make _bin/server/cainjector-linux-$(go env GOARCH)
      make CTR=make _bin/server/acmesolver-linux-$(go env GOARCH)

      mkdir -p ${{targets.destdir}}/usr/bin
      mv _bin/server/* ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: ${{package.name}}-controller
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/controller-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/controller
    dependencies:
      provides:
        - cert-manager-controller=${{package.full-version}}

  - name: ${{package.name}}-webhook
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/webhook-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/webhook
    dependencies:
      provides:
        - cert-manager-webhook=${{package.full-version}}

  - name: ${{package.name}}-cainjector
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/cainjector-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/cainjector
    dependencies:
      provides:
        - cert-manager-cainjector=${{package.full-version}}

  - name: ${{package.name}}-acmesolver
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/acmesolver-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/acmesolver
    dependencies:
      provides:
        - cert-manager-acmesolver=${{package.full-version}}

  - name: cmctl-1.13
    pipeline:
      - runs: |
          make CTR=make cmctl-linux
      - runs: |
          install -Dm755 _bin/cmctl/cmctl-linux-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/cmctl
      - uses: strip
    dependencies:
      provides:
        - cmctl=${{package.full-version}}

update:
  enabled: true
  github:
    identifier: cert-manager/cert-manager
    strip-prefix: v
    tag-filter: v1.13.
    use-tag: true
