package:
  name: emissary
  version: 3.9.1
  epoch: 0
  description: "open source Kubernetes-native API gateway for microservices built on the Envoy Proxy"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - datawire-envoy-privileged
      - git

vars:
  py-pkg: ambassador

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"
      3.13: "300"

environment:
  contents:
    packages:
      - iproute2
      - libcap-utils
      - py3-supported-pip
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/emissary-ingress/emissary
      tag: v${{package.version}}
      expected-commit: 6e2ca35c11d124da26df8dd029c33954960b15ae

  # Go binaries
  - uses: go/build
    with:
      packages: ./cmd/apiext
      output: apiext

  - uses: go/build
    with:
      packages: ./cmd/busyambassador
      output: busyambassador

  - uses: go/build
    with:
      packages: ./cmd/capabilities_wrapper
      output: wrapper

  - name: wrapper-setcap
    # See https://github.com/emissary-ingress/emissary/blob/ac2dc64c6621cd8ec5617f3328544364bdd3fb01/build-aux/Dockerfile#L129-L137
    runs: |
      setcap cap_net_bind_service=p ${{targets.contextdir}}/usr/bin/wrapper

  - uses: go/build
    with:
      packages: ./cmd/kubestatus
      output: kubestatus

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.py-pkg}}
    description: python${{range.key}} version of ${{vars.py-pkg}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.py-pkg}}
    pipeline:
      - runs: |
          # Recommendation is to use the host pip instead of using venv.
          # Pip will complain about being run as root - this disables that warning.
          export PIP_ROOT_USER_ACTION=ignore

          # Install to target dir.
          # Ignore installed packages, since this looks at the builder host packages, when we're trying to install
          # the necessary packages into the target directory.
          python${{range.key}} -m pip install --ignore-installed --prefix=/usr --root=${{targets.contextdir}} -r python/requirements.txt

          # Generate version file - this static file is read by programs to provide version information in logs.
          # See https://github.com/emissary-ingress/emissary/blob/ac2dc64c6621cd8ec5617f3328544364bdd3fb01/python/ambassador/VERSION.py#L26
          make python/ambassador.version
          cp -p python/ambassador.version ${{targets.contextdir}}/usr/lib/python${{range.key}}/site-packages

          # Install Emissary Python package
          cd python
          python${{range.key}} setup.py install --prefix=/usr --root="${{targets.contextdir}}"

          # Install templates - this is not a python package, so it's not installed by the steps above.
          # This contains a set of HTML templates used by the Python code, but is read relative to the module.
          # See https://github.com/emissary-ingress/emissary/blob/ac2dc64c6621cd8ec5617f3328544364bdd3fb01/python/ambassador_diag/diagd.py#L603
          cp -a templates ${{targets.contextdir}}/usr/lib/python${{range.key}}/site-packages/templates
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: from ambassador import Version

  - name: py3-supported-${{vars.py-pkg}}
    description: meta package providing ${{vars.py-pkg}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.py-pkg}}
        - py3.11-${{vars.py-pkg}}
        - py3.12-${{vars.py-pkg}}
        - py3.13-${{vars.py-pkg}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.10
            import: from ambassador import Version

  - name: ${{package.name}}-oci-entrypoint
    description: Entrypoint for ${{package.name}}
    dependencies:
      runtime:
        - emissary
    pipeline:
      - runs: |
          cp -p entrypoint.sh ${{targets.contextdir}}/usr/bin/entrypoint.sh
          chmod +x ${{targets.contextdir}}/usr/bin/entrypoint.sh
    test:
      pipeline:
        - runs: stat /usr/bin/entrypoint.sh

update:
  enabled: true
  github:
    identifier: emissary-ingress/emissary
    strip-prefix: v
    use-tag: true
  ignore-regex-patterns:
    - -rc.*
    - -dev.*
    - ^chart/

test:
  environment:
    contents:
      packages:
        - curl
        - py3-ambassador
  pipeline:
    - uses: python/import
      with:
        imports: from ambassador import Version
    - uses: test/kwok/cluster
    - runs: |
        /usr/bin/entrypoint.sh &

        # Wait for server to come up
        sleep 10

        curl -i http://127.0.0.1:8004/ambassador/v0/check_alive
        curl -i http://127.0.0.1:8004/ambassador/v0/check_ready
