package:
  name: scala-3.4
  version: 3.4.2
  epoch: 0
  description: Scala 2 compiler and standard library.
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - scala=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openjdk-11-default-jvm
      - openjdk-11-jre
      - sbt

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/scala/scala
      tag: v${{package.version}}
      expected-commit: a5270194b6eec9678a79e2f88a83d83aa6b92de1

  - uses: patch
    with:
      patches: builddate.patch

  - runs: |
      sbt setupPublishCore generateBuildCharacterPropertiesFile headerCheck publishLocal dist/mkPack
      install -dm755 "${{targets.destdir}}"/usr/share/scala/bin
      install -dm755 "${{targets.destdir}}"/usr/share/scala/lib
      rm -rf build/pack/bin/*.bat
      mkdir -p ${{targets.destdir}}/usr/bin

      mv build/pack/bin/* ${{targets.destdir}}/usr/share/scala/bin/
      mv build/pack/lib/* ${{targets.destdir}}/usr/share/scala/lib/
      ln -sf /usr/share/scala/bin/scala ${{targets.destdir}}/usr/bin/scala
      ln -sf /usr/share/scala/bin/fsc ${{targets.destdir}}/usr/bin/fsc
      ln -sf /usr/share/scala/bin/scalac ${{targets.destdir}}/usr/bin/scalac
      ln -sf /usr/share/scala/bin/scaladoc ${{targets.destdir}}/usr/bin/scaladoc
      ln -sf /usr/share/scala/bin/scalap ${{targets.destdir}}/usr/bin/scalap

update:
  enabled: true
  github:
    identifier: scala/scala
    strip-prefix: v
    tag-filter-prefix: v3.4
